// components/StaffRow.vue
<template>
  <div :data-staff-id="staff.id" class="flex border-b border-gray-100 bg-white transition-all duration-300 ease-in-out" :style="dynamicStyle">
    <div class="w-64 flex-shrink-0 p-4 border-r border-gray-200 flex flex-col justify-center select-none bg-white relative group z-20 transition-colors hover:bg-gray-50/50" @contextmenu.prevent="onContextStaff" @mousedown.stop @click.stop>
      <div class="absolute left-1 top-1/2 -translate-y-1/2 text-gray-300 p-1 opacity-0 group-hover:opacity-100 rs-staff-handle">≡</div>
      <div class="flex items-center gap-3 pl-4">
        <button class="text-gray-400 hover:text-gray-600" @click="$emit('update-staff', staff.id, { isCollapsed: !staff.isCollapsed })">{{ staff.isCollapsed ? "▸" : "▾" }}</button>
        <slot name="avatar" :staff="staff">
          <img v-if="staff.avatar" :src="staff.avatar" :alt="staff.name" class="w-10 h-10 rounded-full object-cover border border-gray-200 flex-shrink-0 select-none" />
          <div v-else :class="avatarClass" :style="avatarStyle" @click.stop="cycleAvatarColor">{{ staff.name.charAt(0) }}</div>
        </slot>
        <div class="flex-1 min-w-0">
          <div v-if="editingField === 'name'" class="w-full">
            <el-input autofocus size="mini" :value="staff.name" @blur="saveEdit('name', $event)" @keydown.enter.prevent="blurInput" />
          </div>
          <div v-else class="text-sm font-bold text-gray-900 truncate cursor-pointer" @dblclick="startEdit('name')" @click.stop="emitFocus">{{ staff.name }}</div>
          <div v-if="editingField === 'role'" class="w-full">
            <el-input autofocus size="mini" :value="staff.role" @blur="saveEdit('role', $event)" @keydown.enter.prevent="blurInput" />
          </div>
          <div v-else class="text-xs text-gray-500 truncate cursor-text" @dblclick="startEdit('role')">{{ staff.role }}</div>
        </div>
      </div>
      <slot name="workload" v-if="!staff.isCollapsed" :staff="staff"></slot>
    </div>

    <div class="flex-1 relative overflow-hidden bg-white" @contextmenu.prevent="onContextRow">
      <div class="absolute inset-0 grid pointer-events-none" :style="{ gridTemplateColumns: `repeat(${headers.length}, 1fr)` }">
        <div v-for="(h, i) in headers" :key="i" :class="['border-r border-gray-100 h-full', h.isToday ? 'bg-blue-50/60' : h.isWeekend ? 'bg-gray-50/80' : '']"></div>
      </div>
      <div v-if="!staff.isCollapsed" class="relative w-full h-full pt-3 pb-2" @dblclick="onGridDblClick">
        <div v-for="t in staff.tasks" :key="t.id" class="absolute z-10" :style="taskStyle(t)">
          <TaskCard :task="t" :viewMode="viewMode" :readonly="readonly" :conflict="isConflict(t)" @dblclick.native="openEditTask(t)" @contextmenu.native.prevent="onContextTask(t, $event)" @update="onUpdateTaskName(t)" @resize-start="onResizeStart" @mouse-down="onTaskMouseDown" />
        </div>
      </div>
      <div v-else class="absolute inset-0 flex items-center px-2">
        <span class="ml-2 text-xs text-gray-400 whitespace-nowrap bg-white/80 px-2 rounded-full border border-gray-200">{{ staff.tasks.length }} 任务</span>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Staff, Task, DayInfo, ViewMode } from "../types"
import TaskCard from "./TaskCard.vue"
import WorkloadBar from "./WorkloadBar.vue"

export default {
  components: { TaskCard, WorkloadBar },
  props: {
    staff: { type: Object as () => Staff, required: true },
    headers: { type: Array as () => DayInfo[], required: true },
    viewStartDate: { type: Date, required: true },
    viewDurationMs: { type: Number, required: true },
    viewMode: { type: String as () => ViewMode, required: true },
    readonly: { type: Boolean, required: false, default: false },
  },
  data() {
    return { editingField: null as null | "name" | "role" }
  },
  computed: {
    dynamicStyle(): Record<string, string> {
      if (this.staff.isCollapsed) return { height: "64px" }
      const maxRowIndex = this.staff.tasks.length > 0 ? Math.max(...this.staff.tasks.map(t => t.rowOffset)) : 0
      const h = Math.max(128, (maxRowIndex + 2) * 36 + 20)
      return { minHeight: "128px", height: `${h}px` }
    },
    avatarIsColor(): boolean {
      const v = this.staff.avatarColor || ""
      return v.startsWith("#") || v.startsWith("rgb")
    },
    avatarClass(): any {
      const base = ["w-10", "h-10", "rounded-full", "flex", "items-center", "justify-center", "text-sm", "font-bold", "flex-shrink-0", "select-none", "cursor-pointer"]
      return this.avatarIsColor ? base : [...base, this.staff.avatarColor]
    },
    avatarStyle(): any {
      if (!this.avatarIsColor) return {}
      const bg = this.staff.avatarColor
      const hex = bg.startsWith("rgb") ? this.rgbTextToHex(bg) : bg
      const l = this.luminance(hex)
      const color = l > 0.6 ? "#1f2937" : "#ffffff"
      return { backgroundColor: hex, color }
    },
  },
  methods: {
    rgbTextToHex(rgb: string | undefined) {
      if (!rgb) return "#ffffff"
      const m = rgb.match(/rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})(?:\s*,\s*(\d*\.?\d+)\s*)?\)/i)
      if (!m) return rgb
      const to2 = (n: number) => Math.max(0, Math.min(255, n)).toString(16).padStart(2, "0")
      return `#${to2(Number(m[1]))}${to2(Number(m[2]))}${to2(Number(m[3]))}`
    },
    hexToRgb(hex: string) {
      let h = hex.replace("#", "")
      if (h.length === 3)
        h = h
          .split("")
          .map(x => x + x)
          .join("")
      const r = parseInt(h.slice(0, 2), 16),
        g = parseInt(h.slice(2, 4), 16),
        b = parseInt(h.slice(4, 6), 16)
      return { r, g, b }
    },
    luminance(hex?: string) {
      if (!hex) return 0.5
      const { r, g, b } = this.hexToRgb(hex)
      const a = [r, g, b].map(v => {
        const c = v / 255
        return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4)
      })
      return 0.2126 * a[0] + 0.7152 * a[1] + 0.0722 * a[2]
    },
    taskStyle(task: Task) {
      const start = new Date(task.startDate).getTime()
      const startOffset = start - this.viewStartDate.getTime()
      const durationMs = task.duration * 86400000
      let left = (startOffset / this.viewDurationMs) * 100
      let width = (durationMs / this.viewDurationMs) * 100
      const topOffset = (task.rowOffset || 0) * 36
      return { left: `${parseInt(`${left}`)}%`, width: `${Math.max(width, 0.5)}%`, top: `${12 + topOffset}px` }
    },
    startEdit(field: "name" | "role") {
      if (this.readonly) return
      this.editingField = field
    },
    blurInput(e: Event) {
      ;(e.target as HTMLInputElement).blur()
    },
    saveEdit(field: "name" | "role", e: any) {
      const v = String(e.target.value || "").trim()
      if (v) this.$emit("update-staff", this.staff.id, field === "name" ? { name: v } : { role: v })
      this.editingField = null
    },
    emitFocus() {
      this.$emit("focus-staff", this.staff.id)
    },
    cycleAvatarColor() {
      if (this.staff.avatar) return
      const colors = ["bg-blue-100 text-blue-600", "bg-emerald-100 text-emerald-600", "bg-purple-100 text-purple-600", "bg-orange-100 text-orange-600", "bg-rose-100 text-rose-600", "bg-indigo-100 text-indigo-600"]
      const idx = colors.indexOf(this.staff.avatarColor)
      const next = colors[(idx + 1) % colors.length]
      this.$emit("update-staff", this.staff.id, { avatarColor: next })
    },
    onContextStaff(e: MouseEvent) {
      if (this.readonly) return
      this.$emit("context-menu", { clientX: (e as any).clientX, clientY: (e as any).clientY, type: "staff", staffId: this.staff.id })
    },
    onContextRow(e: MouseEvent) {
      if (this.readonly) return
      this.$emit("context-menu", { clientX: (e as any).clientX, clientY: (e as any).clientY, type: "row", staffId: this.staff.id })
    },
    onContextTask(task: Task, e?: MouseEvent) {
      if (this.readonly) return
      const clientX = e ? (e as any).clientX : 0
      const clientY = e ? (e as any).clientY : 0
      this.$emit("context-menu", { clientX, clientY, type: "task", staffId: this.staff.id, taskId: task.id })
    },
    openEditTask(task: Task) {
      if (this.readonly) return
      this.$emit("open-edit-task", task)
    },
    onUpdateTaskName(task: Task) {
      return (newName: string) => this.$emit("update-task", this.staff.id, task.id, { name: newName })
    },
    onResizeStart(e: MouseEvent, dir: "left" | "right", task: Task) {
      if (this.readonly) return
      this.$emit("resize-start", e, dir, task, this.staff.id)
    },
    onTaskMouseDown(e: MouseEvent, task: Task) {
      if (this.readonly) return
      this.$emit("task-mouse-down", task, this.staff.id, e)
    },
    onGridDblClick(e: MouseEvent) {
      if (this.readonly) return
      if ((e.target as HTMLElement).closest(".task-card")) return
      const rowRect = (this.$el as HTMLElement).getBoundingClientRect()
      const timelineLeft = rowRect.left + 260
      const timelineWidth = Math.max(1, rowRect.width - 260)
      const relativeX = e.clientX - timelineLeft
      const msPerPixel = this.viewDurationMs / timelineWidth
      const startMs = (this.viewStartDate as Date).getTime()
      const newStart = startMs + relativeX * msPerPixel
      const d = new Date(newStart)
      d.setHours(0, 0, 0, 0)
      const y = d.getFullYear()
      const m = String(d.getMonth() + 1).padStart(2, "0")
      const day = String(d.getDate()).padStart(2, "0")
      const dateStr = `${y}-${m}-${day}`
      this.$emit("add-task-at", this.staff.id, dateStr)
    },
    isConflict(t: Task): boolean {
      const startA = new Date(t.startDate).getTime()
      const endA = startA + t.duration * 86400000
      return this.staff.tasks.some(
        x =>
          x.id !== t.id &&
          (() => {
            const startB = new Date(x.startDate).getTime()
            const endB = startB + x.duration * 86400000
            return Math.max(startA, startB) < Math.min(endA, endB)
          })()
      )
    },
  },
}
</script>

<style scoped></style>

// components/StaffRow.tsx
import React, { useState } from "react"
import { Staff, Task, DayInfo, ViewMode } from "../types"
import { TaskCard } from "./TaskCard"
import { WorkloadBar } from "./WorkloadBar"
import { ChevronDown, ChevronRight, GripVertical } from "lucide-react"

interface StaffRowProps {
  staff: Staff
  headers: DayInfo[]
  viewStartDate: Date
  viewDurationMs: number
  viewMode: ViewMode
  readonly?: boolean
  renderAvatar?: (staff: Staff) => React.ReactNode
  onStaffDragStart: (e: React.DragEvent, staffId: string) => void
  onStaffDragEnter: (e: React.DragEvent, targetStaffId: string) => void // New: Live sort
  onStaffDrop: (e: React.DragEvent, targetStaffId: string) => void
  onContextMenu: (e: React.MouseEvent, type: "staff" | "task" | "row", staff: Staff, task?: Task) => void
  onToggleCollapse: (staffId: string) => void
  onTaskUpdate: (staffId: string, taskId: string, updates: Partial<Task>) => void
  onResizeStart: (e: React.MouseEvent, direction: "left" | "right", task: Task, staffId: string) => void
  onTaskMouseDown: (e: React.MouseEvent, task: Task, staffId: string) => void
  onStaffUpdate: (staffId: string, updates: Partial<Staff>) => void
}

export const StaffRow: React.FC<StaffRowProps> = ({ staff, headers, viewStartDate, viewDurationMs, viewMode, readonly, renderAvatar, onStaffDragStart, onStaffDragEnter, onStaffDrop, onContextMenu, onToggleCollapse, onTaskUpdate, onResizeStart, onTaskMouseDown, onStaffUpdate }) => {
  const [editingField, setEditingField] = useState<"name" | "role" | null>(null)

  // Determine row height
  const maxRowIndex = staff.tasks.length > 0 ? Math.max(...staff.tasks.map(t => t.rowOffset)) : 0
  const rowHeightClass = staff.isCollapsed ? "h-16" : `min-h-[128px]`
  const dynamicHeight = staff.isCollapsed ? {} : { height: `${Math.max(128, (maxRowIndex + 2) * 36 + 20)}px` }

  // Staff Reordering Handlers
  const handleStaffDragOver = (e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation() // Stop bubbling to prevent parent interference
  }

  // Use DragEnter for Live Sorting (swapping as you drag)
  const handleStaffDragEnter = (e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation() // Stop bubbling to prevent rapid-fire events on children
    onStaffDragEnter(e, staff.id)
  }

  const handleStaffDrop = (e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    onStaffDrop(e, staff.id)
  }

  const cycleAvatarColor = () => {
    // Only cycle color if using the default avatar (no image)
    if (staff.avatar) return

    const colors = ["bg-blue-100 text-blue-600", "bg-emerald-100 text-emerald-600", "bg-purple-100 text-purple-600", "bg-orange-100 text-orange-600", "bg-rose-100 text-rose-600", "bg-indigo-100 text-indigo-600"]
    const currentIdx = colors.indexOf(staff.avatarColor)
    const nextColor = colors[(currentIdx + 1) % colors.length]
    onStaffUpdate(staff.id, { avatarColor: nextColor })
  }

  return (
    <div data-staff-id={staff.id} className={`flex border-b border-gray-100 bg-white transition-all duration-300 ease-in-out ${rowHeightClass}`} style={dynamicHeight}>
      {/* Left Column: Staff Info */}
      <div className="w-64 flex-shrink-0 p-4 border-r border-gray-200 flex flex-col justify-center select-none bg-white relative group z-20 transition-colors hover:bg-gray-50/50" onContextMenu={e => onContextMenu(e, "staff", staff)} onDragOver={handleStaffDragOver} onDragEnter={handleStaffDragEnter} onDrop={handleStaffDrop}>
        <div
          className="absolute left-1 top-1/2 -translate-y-1/2 text-gray-300 cursor-grab hover:text-gray-500 p-1 opacity-0 group-hover:opacity-100 transition-opacity"
          draggable
          onDragStart={e => {
            e.stopPropagation()
            if (!readonly) onStaffDragStart(e, staff.id)
          }} // Stop prop to keep drag clean
        >
          <GripVertical size={16} />
        </div>

        <div className="flex items-center gap-3 pl-4">
          <button
            onClick={e => {
              e.stopPropagation()
              onToggleCollapse(staff.id)
            }}
            className="text-gray-400 hover:text-gray-600 flex-shrink-0"
          >
            {staff.isCollapsed ? <ChevronRight size={16} /> : <ChevronDown size={16} />}
          </button>

          {/* Avatar Logic */}
          {renderAvatar ? (
            <>{renderAvatar(staff)}</>
          ) : staff.avatar ? (
            <img src={staff.avatar} alt={staff.name} className="w-10 h-10 rounded-full object-cover border border-gray-200 flex-shrink-0 select-none" />
          ) : (
            <div
              className={`w-10 h-10 rounded-full flex items-center justify-center text-sm font-bold ${staff.avatarColor} cursor-pointer hover:ring-2 ring-offset-1 ring-indigo-200 flex-shrink-0 select-none`}
              onClick={() => {
                if (!readonly) cycleAvatarColor()
              }}
              title="点击切换颜色"
            >
              {staff.name.charAt(0)}
            </div>
          )}

          <div className="flex-1 min-w-0">
            {editingField === "name" ? (
              <input
                autoFocus
                className="w-full text-sm font-bold border rounded px-1"
                defaultValue={staff.name}
                onBlur={e => {
                  if (!readonly && e.target.value.trim()) onStaffUpdate(staff.id, { name: e.target.value })
                  setEditingField(null)
                }}
                onKeyDown={e => {
                  if (e.key === "Enter") e.currentTarget.blur()
                }}
              />
            ) : (
              <div
                className="text-sm font-bold text-gray-900 truncate cursor-text hover:text-indigo-600"
                onDoubleClick={() => {
                  if (!readonly) setEditingField("name")
                }}
                title="双击编辑"
              >
                {staff.name}
              </div>
            )}

            {editingField === "role" ? (
              <input
                autoFocus
                className="w-full text-xs text-gray-500 border rounded px-1"
                defaultValue={staff.role}
                onBlur={e => {
                  if (!readonly && e.target.value.trim()) onStaffUpdate(staff.id, { role: e.target.value })
                  setEditingField(null)
                }}
                onKeyDown={e => {
                  if (e.key === "Enter") e.currentTarget.blur()
                }}
              />
            ) : (
              <div
                className="text-xs text-gray-500 truncate cursor-text hover:text-indigo-600"
                onDoubleClick={() => {
                  if (!readonly) setEditingField("role")
                }}
                title="双击编辑"
              >
                {staff.role}
              </div>
            )}
          </div>
        </div>
        {!staff.isCollapsed && <WorkloadBar percentage={staff.workloadPercentage} />}
      </div>

      {/* Right Column: Timeline Grid */}
      <div
        className="flex-1 relative overflow-hidden bg-white"
        onContextMenu={e => {
          if ((e.target as HTMLElement).closest(".task-card")) return
          onContextMenu(e, "row", staff)
        }}
      >
        {/* Background Grid */}
        <div className="absolute inset-0 grid pointer-events-none" style={{ gridTemplateColumns: `repeat(${headers.length}, 1fr)` }}>
          {headers.map((h, i) => (
            <div key={i} className={`border-r border-gray-100 h-full ${h.isToday ? "bg-blue-50/60" : h.isWeekend ? "bg-gray-50/80" : ""}`} />
          ))}
        </div>

        {/* Tasks Layer */}
        {!staff.isCollapsed && (
          <div className="relative w-full h-full pt-3 pb-2">
            {staff.tasks.map(task => {
              const taskStart = new Date(task.startDate).getTime()
              const startOffset = taskStart - viewStartDate.getTime()
              const durationMs = task.duration * 86400000

              let left = (startOffset / viewDurationMs) * 100
              let width = (durationMs / viewDurationMs) * 100

              if (left + width < -50 || left > 150) return null

              const topOffset = (task.rowOffset || 0) * 36

              return (
                <div
                  key={task.id}
                  className="absolute z-10"
                  style={{
                    left: `${parseInt(`${left}`)}%`,
                    width: `${Math.max(width, 0.5)}%`,
                    top: `${12 + topOffset}px`,
                  }}
                >
                  <TaskCard task={task} viewMode={viewMode} readonly={readonly} onMouseDown={e => onTaskMouseDown(e, task, staff.id)} onContextMenu={e => onContextMenu(e, "task", staff, task)} onUpdate={newName => onTaskUpdate(staff.id, task.id, { name: newName })} onResizeStart={(e, dir, t) => onResizeStart(e, dir, t, staff.id)} />
                </div>
              )
            })}
          </div>
        )}

        {/* Collapsed Summary */}
        {staff.isCollapsed && staff.tasks.length > 0 && (
          <div className="absolute inset-0 flex items-center px-2">
            <span className="ml-2 text-xs text-gray-400 whitespace-nowrap bg-white/80 px-2 rounded-full border border-gray-200">{staff.tasks.length} 任务</span>
          </div>
        )}
      </div>
    </div>
  )
}
