// components/TaskCard.vue
<template>
  <div class="task-card group relative flex items-center h-7 rounded px-1 transition-shadow shadow-sm" :class="conflict ? 'border border-rose-400' : ''" :style="{ overflow: 'visible', backgroundColor: bg }" @dblclick.stop="startEdit" @contextmenu.stop.prevent="$emit('contextmenu', task)" @mousedown="onMouseDown">
    <div v-if="!editing && !readonly" class="absolute left-0 top-0 bottom-0 w-2 cursor-w-resize z-20 hover:bg-indigo-400/50 rounded-l" @mousedown.stop="emitResize('left', $event)"></div>
    <span class="text-[10px] font-bold mr-1.5 whitespace-nowrap select-none ml-1 flex-shrink-0 z-10" :style="{ color: text }">{{ task.id }}</span>
    <input v-if="editing" ref="inputRef" type="text" v-model="editValue" @blur="commit" @keydown.enter.prevent="commit" @keydown.esc.prevent="cancel" class="flex-1 bg-white text-[10px] px-1 py-0.5 border-none outline-none text-indigo-900 rounded h-5 min-w-0 z-10" />
    <template v-else>
      <div v-if="showOutside" class="absolute left-full ml-1 top-1/2 -translate-y-1/2 whitespace-nowrap text-[10px] font-medium pointer-events-none z-0" :style="{ color: text }">{{ task.name }}</div>
      <div v-else class="flex-1 overflow-hidden relative h-full flex items-center z-10">
        <div class="whitespace-nowrap text-[10px] font-medium truncate" :style="{ color: text }">{{ task.name }}</div>
      </div>
    </template>
    <div v-if="!editing && !readonly" class="absolute right-0 top-0 bottom-0 w-2 cursor-e-resize z-20 hover:bg-indigo-400/50 rounded-r" @mousedown.stop="emitResize('right', $event)"></div>
  </div>
</template>

<script lang="ts">
import { Task, ViewMode } from "../types"
import { DEFAULT_TASK_BG, DEFAULT_TASK_TEXT } from "../constants"

export default {
  props: {
    task: { type: Object as () => Task, required: true },
    viewMode: { type: String as () => ViewMode, required: true },
    readonly: { type: Boolean, required: false, default: false },
    conflict: { type: Boolean, required: false, default: false },
  },
  data() {
    return { editing: false, editValue: (this as any).task.name }
  },
  computed: {
    bg(): string {
      return this.task.bgColor || DEFAULT_TASK_BG
    },
    text(): string {
      return this.task.textColor || DEFAULT_TASK_TEXT
    },
    showOutside(): boolean {
      if (this.viewMode === "month") return this.task.duration < 2.5
      if (this.viewMode === "quarter") return this.task.duration < 7
      if (this.viewMode === "year") return this.task.duration < 15
      return false
    },
  },
  methods: {
    startEdit() {
      if (this.readonly) return
      this.editing = true
      this.editValue = this.task.name
      this.$nextTick(() => {
        const i = this.$refs.inputRef as HTMLInputElement
        i && i.focus()
      })
    },
    commit() {
      this.editing = false
      if (this.readonly) return
      const v = this.editValue.trim()
      if (v && v !== this.task.name) this.$emit("update", v)
    },
    cancel() {
      this.editing = false
      this.editValue = this.task.name
    },
    onMouseDown(e: MouseEvent) {
      if (this.readonly || this.editing || (e as any).button !== 0) return
      this.$emit("mouse-down", e, this.task)
    },
    emitResize(direction: "left" | "right", e: MouseEvent) {
      this.$emit("resize-start", e, direction, this.task)
    },
  },
}
</script>

<style scoped></style>

// components/TaskCard.tsx
import React, { useState, useRef, useEffect } from "react"
import { Task, ViewMode } from "../types"
import { DEFAULT_TASK_BG, DEFAULT_TASK_TEXT } from "../constants"

interface TaskCardProps {
  task: Task
  viewMode: ViewMode
  readonly?: boolean
  onContextMenu: (e: React.MouseEvent, task: Task) => void
  onUpdate: (newName: string) => void
  onResizeStart: (e: React.MouseEvent, direction: "left" | "right", task: Task) => void
  onMouseDown: (e: React.MouseEvent, task: Task) => void
}

export const TaskCard: React.FC<TaskCardProps> = ({ task, viewMode, readonly, onContextMenu, onUpdate, onResizeStart, onMouseDown }) => {
  const [isEditing, setIsEditing] = useState(false)
  const [editValue, setEditValue] = useState(task.name)
  const inputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    if (isEditing && inputRef.current) {
      inputRef.current.focus()
    }
  }, [isEditing])

  const handleDoubleClick = (e: React.MouseEvent) => {
    e.stopPropagation()
    if (readonly) return
    setIsEditing(true)
    setEditValue(task.name)
  }

  const handleBlur = () => {
    setIsEditing(false)
    if (editValue.trim() && editValue !== task.name) {
      onUpdate(editValue.trim())
    } else {
      setEditValue(task.name)
    }
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") {
      handleBlur()
    } else if (e.key === "Escape") {
      setIsEditing(false)
      setEditValue(task.name)
    }
  }

  const handleMouseDown = (e: React.MouseEvent) => {
    if (isEditing || e.button !== 0) return
    if (readonly) return
    onMouseDown(e, task)
  }

  const isTooSmallForText = () => {
    if (viewMode === "month") return task.duration < 2.5
    if (viewMode === "quarter") return task.duration < 7
    if (viewMode === "year") return task.duration < 15
    return false
  }
  const showOutside = isTooSmallForText()

  const effectiveBg = task.bgColor ?? DEFAULT_TASK_BG
  const effectiveText = task.textColor ?? DEFAULT_TASK_TEXT
  const bgStyle = { backgroundColor: effectiveBg }
  const idTextStyle = { color: effectiveText }
  const nameTextStyle = { color: effectiveText }

  return (
    <div className={`task-card group relative flex items-center h-7 rounded px-1 transition-shadow shadow-sm ${isEditing ? "ring-2 ring-indigo-500 z-50" : "cursor-grab active:cursor-grabbing hover:brightness-95 hover:shadow-md"}`} style={{ overflow: "visible", ...bgStyle }} draggable={false} onMouseDown={handleMouseDown} onContextMenu={e => onContextMenu(e, task)} onDoubleClick={handleDoubleClick}>
      {/* Resize Handle Left */}
      {!isEditing && !readonly && (
        <div
          className="absolute left-0 top-0 bottom-0 w-2 cursor-w-resize z-20 hover:bg-indigo-400/50 rounded-l"
          onMouseDown={e => {
            e.stopPropagation()
            onResizeStart(e, "left", task)
          }}
        />
      )}

      {/* Content */}
      <span className="text-[10px] font-bold mr-1.5 whitespace-nowrap select-none ml-1 flex-shrink-0 z-10" style={idTextStyle}>
        {task.id}
      </span>

      {isEditing ? (
        <input ref={inputRef} type="text" value={editValue} onChange={e => setEditValue(e.target.value)} onBlur={handleBlur} onKeyDown={handleKeyDown} className="flex-1 bg-white text-[10px] px-1 py-0.5 border-none outline-none text-indigo-900 rounded h-5 min-w-0 z-10" />
      ) : (
        <>
          {showOutside ? (
            // Text Outside (to the right)
            <div className="absolute left-full ml-1 top-1/2 -translate-y-1/2 whitespace-nowrap text-[10px] font-medium pointer-events-none z-0" style={nameTextStyle}>
              {task.name}
            </div>
          ) : (
            // Text Inside (Marquee or Truncate)
            <div className="flex-1 overflow-hidden relative h-full flex items-center z-10">
              <div className="whitespace-nowrap text-[10px] font-medium absolute group-hover:animate-marquee" style={nameTextStyle}>
                {task.name}
              </div>
              <div className="whitespace-nowrap text-[10px] font-medium opacity-100 group-hover:opacity-0 truncate" style={nameTextStyle}>
                {task.name}
              </div>
            </div>
          )}
        </>
      )}

      {/* Resize Handle Right */}
      {!isEditing && !readonly && (
        <div
          className="absolute right-0 top-0 bottom-0 w-2 cursor-e-resize z-20 hover:bg-indigo-400/50 rounded-r"
          onMouseDown={e => {
            e.stopPropagation()
            onResizeStart(e, "right", task)
          }}
        />
      )}
    </div>
  )
}
